name: Generate Third-Party Licenses

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-licenses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # 対応バージョンに変更可（4.8 はCLI非対応なのでOK）

      - name: Install dotnet-project-licenses
        run: dotnet tool install --global dotnet-project-licenses

      - name: Generate THIRD_PARTY_NOTICES.md
        run: |
          cd FlexGridWPF
          dotnet project-licenses generate --output-file ../THIRD_PARTY_NOTICES.md --format markdown

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ../THIRD_PARTY_NOTICES.md
          git diff --quiet && echo "No changes" || git commit -m "Update THIRD_PARTY_NOTICES.md"
          git push
          
 