name: Generate Third-Party Licenses for each project

on:
  push:
    branches:
      - master
      - main
      
  workflow_dispatch:

jobs:
  generate-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #- name: Setup .NET (7.0 and 8.0)
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version:
      #       8.0.x
      #       7.0.x
      #    dotnet-quality: 'ga'

      # - name: Set DOTNET_ROOT
      #  run: echo \"DOTNET_ROOT=$HOME/.dotnet\" >> $GITHUB_ENV
      
      - name: Install .NET 7.0 SDK locally
        run: |
          wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 7.0 --install-dir "$HOME/.dotnet"

      - name: Set DOTNET_ROOT and update PATH
        run: |
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Check installed SDKs and runtimes (debug)
        run: |
          dotnet --list-sdks
          dotnet --list-runtimes

      - name: Install license tool
        run: dotnet tool install --global dotnet-project-licenses

      - name: Check working directory
        run: pwd # -> /home/runner/work/FlexoGridWPF/FlexoGridWPF 

      # /home/runner/work/
      #  └── リポジトリ名/       ← 作業ルート
      #       └── リポジトリ名/  ← Gitの中身
      #
      # .github/workflows/generate-licenses.yml がある場所と FlexoGridWPF/ フォルダがある場所
      # [GitRoot] = /home/runner/work/FlexoGridWPF/FlexoGridWPF/ として、
      # [GitRoot].github/workflows/generate-licenses.yml
      # [GitRoot]FlexoGridWPF/ →プロジェクト FlexoGridWPF/ フォルダがある場所
      #
      # pwd -> "/home/runner/work/FlexoGridWPF/FlexoGridWPF" == [GitRoot] 

      # Could not find a part of the path 
      # '[/home/runner/work/FlexoGridWPF/FlexoGridWPF/]FlexoGridWPF/FlexoGridWPF.csproj'.
      - name: Generate for FlexoGridWPF
        run: |
          cd ..
          dotnet-project-licenses --input ../FlexoGridWPF/FlexoGridWPF.csproj --md --outfile THIRD_PARTY_FlexoGridWPF.md

      - name: Generate for FlexoGrid (sample app)
        run: |
          cd ..
          dotnet-project-licenses --input FlexoGrid/FlexoGrid.csproj --md --outfile THIRD_PARTY_FlexoGrid.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Update third-party license files"
          git push