name: Generate Third-Party Licenses for each project

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  generate-licenses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET 7.0 runtime locally
        run: |
          wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --runtime dotnet --version 7.0.17 --install-dir "$HOME/.dotnet"

      - name: Set DOTNET_ROOT and update PATH
        run: |
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Check installed runtimes (debug)
        run: dotnet --list-runtimes

      - name: Install license tool
        run: dotnet tool install --global dotnet-project-licenses

      - name: Check working directory
        run: pwd # -> /home/runner/work/FlexoGridWPF/FlexoGridWPF

      - name: Generate licenses for FlexoGridWPF
        run: |
          cd ../FlexoGridWPF
          dotnet project-licenses generate --output-file THIRD_PARTY_FlexoGridWPF.md --format markdown
          cd ..

      - name: Generate licenses for FlexoGrid (sample app)
        run: |
          cd ../FlexoGrid
          dotnet project-licenses generate --output-file THIRD_PARTY_FlexoGrid.md --format markdown
          cd ..

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Update third-party license files"
          git push