name: Generate Third-Party Licenses for each project

on:
  push:
    branches:
      - master
      - main
      
  workflow_dispatch:

jobs:
  generate-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install license tool
        run: dotnet tool install --global dotnet-project-licenses

     - name: Root Folder
        run: cd ..
             cd ..
        
      - name: Generate for FlexoGridWPF
        run: |
          cd FlexoGridWPF
          dotnet project-licenses generate --output-file THIRD_PARTY_FlexoGridWPF.md --format markdown
          cd ..

      - name: Generate for FlexoGrid (sample app)
        run: |
          cd FlexoGrid
          dotnet project-licenses generate --output-file THIRD_PARTY_FlexoGrid.md --format markdown
          cd ..

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Update third-party license files"
          git push
